import type { Metadata } from "next";
import localFont from "next/font/local";
import { Navbar, Footer, WhatsAppChat } from '@/components';

import "./globals.css";

// In your component or page (e.g., Navbar.js)
import '@/css/animate.css';
import '@/css/bootstrap.css';
import '@/css/flexslider.css';
import '@/css/icomoon.css';
import '@/css/magnific-popup.css';
import '@/css/owl.carousel.min.css';
import '@/css/owl.theme.default.min.css';
import '@/css/pricing.css';
import '@/css/style.css';
import Script from "next/script";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar></Navbar>
        <WhatsAppChat></WhatsAppChat>
        {children}
        <Footer></Footer>



        {/* Load jQuery first */}
        <Script src="/js/jquery.min.js" strategy="beforeInteractive" />

        {/* Load Bootstrap after jQuery */}
        <Script src="/js/bootstrap.min.js" strategy="afterInteractive" />

        {/* Load Owl Carousel after jQuery */}
        <Script src="/js/owl.carousel.min.js" strategy="afterInteractive" />

        {/* Load Google Maps API with your API key */}
        <Script
          src={`https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap`}
          strategy="afterInteractive"
        />

        {/* Load other JavaScript files */}
        <Script src="/js/google_map.js" strategy="afterInteractive" />
        <Script src="/js/jquery.countTo.js" strategy="afterInteractive" />
        <Script src="/js/jquery.easing.1.3.js" strategy="afterInteractive" />
        <Script src="/js/jquery.flexslider-min.js" strategy="afterInteractive" />
        <Script src="/js/jquery.magnific-popup.min.js" strategy="afterInteractive" />
        <Script src="/js/jquery.stellar.min.js" strategy="afterInteractive" />
        <Script src="/js/jquery.waypoints.min.js" strategy="afterInteractive" />
        <Script src="/js/magnific-popup-options.js" strategy="afterInteractive" />
        <Script src="/js/main.js" strategy="afterInteractive" />
        <Script src="/js/modernizr-2.6.2.min.js" strategy="afterInteractive" />
        <Script src="/js/respond.min.js" strategy="afterInteractive" />
        <Script src="/js/simplyCountdown.js" strategy="afterInteractive" />

      </body>
    </html>
  );
}
