import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import "./globals.css";

// In your component or page (e.g., Navbar.js)
import '@/css/animate.css';
import '@/css/bootstrap.css';
import '@/css/flexslider.css';
import '@/css/icomoon.css';
import '@/css/magnific-popup.css';
import '@/css/owl.carousel.min.css';
import '@/css/owl.theme.default.min.css';
import '@/css/pricing.css';
import '@/css/style.css';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
